"""remove constrait nullable

Revision ID: 988a84341f66
Revises: 58add4e1f6ef
Create Date: 2024-11-17 21:21:44.286749

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "988a84341f66"
down_revision: Union[str, None] = "58add4e1f6ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "user_timezone_offset",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "user_timezone_offset",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
