"""change columns names, move notification_advance_time column

Revision ID: 58add4e1f6ef
Revises: df84c8a54911
Create Date: 2024-11-17 20:02:29.970120

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "58add4e1f6ef"
down_revision: Union[str, None] = "df84c8a54911"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification",
        sa.Column(
            "created_at_utc",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "notification",
        sa.Column("event_time_utc", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "notification",
        sa.Column("notification_advance_time", sa.Integer(), nullable=False),
    )
    op.drop_column("notification", "event_time")
    op.drop_column("notification", "created_at")
    op.add_column(
        "user",
        sa.Column(
            "created_at_utc",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "user", sa.Column("user_timezone_offset", sa.Integer(), nullable=False)
    )
    op.drop_column("user", "minutes_before_noti")
    op.drop_column("user", "created_at")
    op.drop_column("user", "timezone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "timezone", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "minutes_before_noti",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("user", "user_timezone_offset")
    op.drop_column("user", "created_at_utc")
    op.add_column(
        "notification",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "notification",
        sa.Column(
            "event_time",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("notification", "notification_advance_time")
    op.drop_column("notification", "event_time_utc")
    op.drop_column("notification", "created_at_utc")
    # ### end Alembic commands ###
